规则设置文件
搜索引擎名称 ¦ 搜索URL地址 ¦ 开始截取 ¦ 结束截取
Google.com|http://www.google.com/search?q=site%3A|of about <b>|</b>
Google.cn|http://www.google.cn/search?q=site%3A|总共约为 <b>|</b>
Baidu.com|http://www.baidu.com/s?wd=site%3A|找到相关网页约|篇
Sogou.com|http://www.sogou.com/web?query=site%3A|<span>找到 | 个网页
Live.com|http://search.live.com/results.aspx?q=site%3A|Page 1 of |results
SOSO.com|http://www.soso.com/q?pid=s.idx&w=site%3A|搜索到约|项结果
163.com|http://so.163.com/search.php?keyWord=&q=site%3A|的结果约 <b>|</b> 条
ZhongSou|http://p.zhongsou.com/p?w=site%3A|"38%">找到|条结果
Yahoo.com.cn|http://sitemap.cn.yahoo.com/search?p=http%3A%2F%2F|被收录的网页： 共 <strong>|</strong> 条
Yahoo.com|http://siteexplorer.search.yahoo.com/search?p=http%3A%2F%2F|of about <strong>|</strong>
Alexa|http://www.alexa.com/search?q=site%3A|</strong> of about|</strong>